### ISSUE TITLE
Sites no longer displaying properly

### ISSUE THREAD

**Issue by wsmelton** [dataplat/dataplat.github.io#14]
![image](https://user-images.githubusercontent.com/11204251/65965100-a97c6180-e423-11e9-99b4-f139c76203a7.png)

Believe this line is the problem:

https://github.com/sqlcollaborative/sqlcollaborative.github.io/blob/ab734a5d99d79c9123cb235e0a24322a9dfd5649/boh.html#L351-L353

When loading page dev tools show this error:

> builds:13 GET https://cdn.datatables.net/v/bs4-4.0.0-beta/jq-3.2.1/jq-3.2.1/jszip-2.5.0/dt-1.10.16/b-1.4.2/b-html5-1.4.2/fh-3.1.3/r-2.2.0/datatables.min.css net::ERR_ABORTED 404

**Comment by niphlod** [comment]
fixed, thanks for the report
