### ISSUE TITLE
Add file version

### ISSUE THREAD

**Issue by ErikEJ** [dataplat/dataplat.github.io#2]
This is what I have been looking for for months, sadly it was not visible until now.

In order to use this for my purpose, I need the sqlserver.exe file version for each build, usually in the format: 

2015.131.5153.0  and 2017.140.3030.27

Would you be interested in a PR that adds this information to the file.

Proposed property name:

Ver 
(to keep json file smaller)
or FileVersion

What do you think?

**Comment by wsmelton** [comment]
The exe file version is not required to match the actual build number of SQL Server. Adding that property would be a lot of time to go and verify the version matches on each build for all versions we have in the json file right now.

We do not map the version of the exe file to the patch release of SQL Server at this time in dbatools module (this project is tied to that), but I will let others reply on their opinion.

**Comment by ErikEJ** [comment]
For my purpose I only have the file version, and on the basis of that I would like to determine patch status. This does not require me to log in to a SQL engine, only file system read access!

**Comment by ErikEJ** [comment]
Also, I will be happy to provide file version numbers in a PR..

**Comment by wsmelton** [comment]
The file version again is not guaranteed to be the same build version though.

I would have to disagree with adding that information as it is not pertinent. It is standard to validate the build of an instance by logging in to it and pulling it from there. Microsoft support for example will not go off the file version on support case.

You can also get the version from the register and not have to depend on the file version of you do not want to log in to an instance.

**Comment by rabryst** [comment]
Erik, for your purposes I'd suggest forking the code and creating your own project that includes file version.

**Comment by ErikEJ** [comment]
@rabryst that would defeat the purpose of having a single file maintained centrally.

@wsmelton sqlserverbuilds lists file versions and build versions, so I do not understand your concern
