### ISSUE TITLE
Author

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dataplat.github.io#5]
Can the author be added to docs? I'll add myself as an author to ensure each command has an author.

and perhaps "if there is an @, add their twitter, otherwise, link a website?" not sure if that's possible or a good idea.

**Comment by niphlod** [comment]
we can, the author bit is nicely parsed already if there is one, just need to add to the resulting html

**Comment by niphlod** [comment]
take a look at https://github.com/sqlcollaborative/docs/commit/741d5d94b13bfdfa6b90cd0a25b5d241495686ae, which is the new master. post there any further requirement ^_^, going to close this
