### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dataplat.github.io#6]
Can we get some spacing between the command name and synopsis?

I looked at the code and suppose it should be taken care of by \n\n\n but it's a lil too close.

**Comment by niphlod** [comment]
we can, I'll look into it in 24 hours

**Comment by niphlod** [comment]
take a look at https://github.com/sqlcollaborative/docs/commit/741d5d94b13bfdfa6b90cd0a25b5d241495686ae, which is the new master. post there any further requirement ^_^, going to close this
