### ISSUE TITLE
alignment

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dataplat.github.io#7]
can the alignment of download, etc, but right justified? also, is there a way to preview my changes?

**Comment by niphlod** [comment]
you can host the html and the index file, it's a static page, nothing more than a static-serving server is needed ^_^

**Comment by niphlod** [comment]
Missed the meaning of "alignment of download,etc but right justified" ..... what does need right alignment ?

**Comment by niphlod** [comment]
right aligment of menu plus hamburger pushed
