### ISSUE TITLE
Consideration in generating more accessibility friendly site/view

### ISSUE THREAD

**Issue by wsmelton** [dataplat/dataplat.github.io#8]
I'm sure this was discussed in Slack and I likely missed it or just plan forgot the end result of the discussion...

Was any testing/review done using currently published automated tools for generating the docs? Mind you this would be tools that would not be parsing the json file we have for the Find command.

One I have played with before is [psDoc](https://github.com/chaseflorell/psdoc) script that seems to work pretty well.

Full view:
![image](https://user-images.githubusercontent.com/11204251/45302365-bfe21300-b4d8-11e8-8f00-2a416daf206d.png)

Mobile view:
![image](https://user-images.githubusercontent.com/11204251/45302372-c4a6c700-b4d8-11e8-9f71-5048e80370b6.png)

If we want to stick with the current code is fine we just need to have it documented to know how it will be updated when we get the CI process written/published (hopefully will be by EOY based on schedule/availability).

**Comment by niphlod** [comment]
anyone with a streamlined solution that does not burden any person maintaining the +1 copy of the docs is welcome. 
this is just an (my) alpha using what we had already. To keep everything updated all it takes is for @cl to push here what gets pushed to the main repo already, to "sustain" find-dbacommand. it's the same json file that fuels both.
Looking at psdoc it doesn't make that much more than the js on the current page. As for parameters documentation, which is missing, we can surely add but goal was to get on par with the current docs, which did not contain params docs.

**Comment by potatoqualitee** [comment]
i'd love the params, it'd prompt us to better standardize too. i did a little bit of work on sqlinstance and sqlcredential but we have more to go. 

if we can get the colors to alternate between like the params example above that'd e cool too.

I like the above output, including that alias section, but psdocs hasnt been updated in a year, and it also uses js and regex parsing.

I'm not sure the module offers much to unburden @niphlod.

**Comment by wsmelton** [comment]
Just coming back around to this....

@niphlod not sure I follow how parameter documentation is missing from psdoc, it is included in the screenshot provided?

**Comment by niphlod** [comment]
was missing from ours, not psdoc's

**Comment by niphlod** [comment]
btw, this 'can' be closed, if noone chimes in more
